### ISSUE TITLE
Telnet wont open

### ISSUE THREAD

**Issue by sorakamid2** [douniwan5788/zte_modem_tools#14]
python3 zte_factroymode.py --user super --pass yQwjrtt2h25n --ip 192.168.100.1 --port 80 telnet open
trying  user:"super" pass:"yQwjrtt2h25n" 
reset facTelnetSteps:
Traceback (most recent call last):
  File "/home/kali/.venv/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.venv/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/kali/.venv/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/kali/.venv/lib/python3.11/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.11/http/client.py", line 1303, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1349, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1298, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1058, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 996, in send
    self.connect()
  File "/home/kali/.venv/lib/python3.11/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/home/kali/.venv/lib/python3.11/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f16baf03d10>, 'Connection to 192.168.100.1 timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/.venv/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/kali/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/kali/.venv/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.100.1', port=80): Max retries exceeded with url: /webFac (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f16baf03d10>, 'Connection to 192.168.100.1 timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/zte_modem_tools/zte_factroymode.py", line 318, in <module>
    main()
  File "/home/kali/zte_modem_tools/zte_factroymode.py", line 314, in main
    dealTelnet(args.ip, args.port, args.user, args.pw, args.action)
  File "/home/kali/zte_modem_tools/zte_factroymode.py", line 270, in dealTelnet
    telnet = dealFacAuth(WebFacTelnet, ip, port, users, pws)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/zte_modem_tools/zte_factroymode.py", line 221, in dealFacAuth
    if webfac.reset():
       ^^^^^^^^^^^^^^
  File "/home/kali/zte_modem_tools/zte_factroymode.py", line 59, in reset
    resp = self.S.post(f"http://{self.ip}:{self.port}/webFac", data='SendSq.gch')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.venv/lib/python3.11/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.venv/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.venv/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/.venv/lib/python3.11/site-packages/requests/adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='192.168.100.1', port=80): Max retries exceeded with url: /webFac (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f16baf03d10>, 'Connection to 192.168.100.1 timed out. (connect timeout=None)'))

**Comment by marcuskhan005** [comment]
bro router is not responding on telnet what to do

**Comment by hrizkiou** [comment]
i think you need to use the user and password written on the back of the router when trying to execute the first cmd

**Comment by justinmihigo** [comment]
encountering the same error any body solved this, help us
